openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contacts management application>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <With help of this application you may create, modify and delete contact records>
tags:
  # теги, що ви будете використовувати
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-application-0knp.onrender.com
paths:
  # ********** Get all contacts ***************
  /students:
    get:
      $ref: ../swagger/paths/contacts/get.yaml

  # ********** Get contacts by id *************
  /contact/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
